services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: yada
      POSTGRES_PASSWORD: password
      POSTGRES_DB: yada
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

